spring:
  application:
    name: graphql-gateway
  graphql:
    http:
      path: /graphql
    graphiql:
      enabled: true
      path: /graphiql

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
