name: CI - Front & Back

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-alibabos
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build et analyse (Checkstyle, SpotBugs, PMD + tests)
        run: mvn clean verify
